name: Track GitHub Followers

on:
  schedule:
    # Runs at 12:00, between day 1 and 31 of the month
    - cron: '0 12 1-31 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-followers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Git credentials
        run: |
          git config --global user.name "${{github.repository_owner}}"
          git config --global user.email "$(gh api user/public_emails -q '.[0].email')"
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Track followers         
        run: uv run track_followers.py ${{ github.repository_owner }}
      
      - name: Commit and push changes
        run: |
          BRANCH="update/$(date +%Y-%m-%d)"
          git switch --create "${BRANCH}"
          git add -A
          if git diff --staged --quiet; then
            echo "No changed files to commit"
          else
            git commit --signoff -m "chore: update follower data for $(date +%Y-%m-%d)"
            git push origin "${BRANCH}"
            gh pr create \
              --base main \
              --head "${BRANCH}" \
              --title "chore: update follower data for $(date +%Y-%m-%d)" \
              --reviewer ${{github.repository_owner}} \
              --assignee ${{github.repository_owner}} \
              --label "documentation"
          fi
